server {
    listen 80;
    server_name 80.242.57.219;
    location /_next/static/ {
        alias /var/www/wannabe/.next/static/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    location /images/ {
        alias /var/www/wannabe/public/images/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    location /fonts/ {
        alias /var/www/wannabe/public/fonts/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    location /icons/ {
        alias /var/www/wannabe/public/icons/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
