name: Deploy to VPS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 80.242.57.219
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/wannabe
            git pull
            npm install
            npm run build
            pm2 restart wannabe
